sudo: required

services:
  - docker

before_install:
  - docker build -t pedux23/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pedux23/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-725392039863"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  